// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIIsilon) DeepCopyInto(out *CSIIsilon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIIsilon.
func (in *CSIIsilon) DeepCopy() *CSIIsilon {
	if in == nil {
		return nil
	}
	out := new(CSIIsilon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIIsilon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIIsilonList) DeepCopyInto(out *CSIIsilonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIIsilon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIIsilonList.
func (in *CSIIsilonList) DeepCopy() *CSIIsilonList {
	if in == nil {
		return nil
	}
	out := new(CSIIsilonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIIsilonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIIsilonSpec) DeepCopyInto(out *CSIIsilonSpec) {
	*out = *in
	in.Driver.DeepCopyInto(&out.Driver)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIIsilonSpec.
func (in *CSIIsilonSpec) DeepCopy() *CSIIsilonSpec {
	if in == nil {
		return nil
	}
	out := new(CSIIsilonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerMax) DeepCopyInto(out *CSIPowerMax) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerMax.
func (in *CSIPowerMax) DeepCopy() *CSIPowerMax {
	if in == nil {
		return nil
	}
	out := new(CSIPowerMax)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIPowerMax) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerMaxList) DeepCopyInto(out *CSIPowerMaxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIPowerMax, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerMaxList.
func (in *CSIPowerMaxList) DeepCopy() *CSIPowerMaxList {
	if in == nil {
		return nil
	}
	out := new(CSIPowerMaxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIPowerMaxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerMaxRevProxy) DeepCopyInto(out *CSIPowerMaxRevProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerMaxRevProxy.
func (in *CSIPowerMaxRevProxy) DeepCopy() *CSIPowerMaxRevProxy {
	if in == nil {
		return nil
	}
	out := new(CSIPowerMaxRevProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIPowerMaxRevProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerMaxRevProxyList) DeepCopyInto(out *CSIPowerMaxRevProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIPowerMaxRevProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerMaxRevProxyList.
func (in *CSIPowerMaxRevProxyList) DeepCopy() *CSIPowerMaxRevProxyList {
	if in == nil {
		return nil
	}
	out := new(CSIPowerMaxRevProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIPowerMaxRevProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerMaxRevProxySpec) DeepCopyInto(out *CSIPowerMaxRevProxySpec) {
	*out = *in
	in.RevProxy.DeepCopyInto(&out.RevProxy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerMaxRevProxySpec.
func (in *CSIPowerMaxRevProxySpec) DeepCopy() *CSIPowerMaxRevProxySpec {
	if in == nil {
		return nil
	}
	out := new(CSIPowerMaxRevProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerMaxRevProxyStatus) DeepCopyInto(out *CSIPowerMaxRevProxyStatus) {
	*out = *in
	in.ProxyStatus.DeepCopyInto(&out.ProxyStatus)
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerMaxRevProxyStatus.
func (in *CSIPowerMaxRevProxyStatus) DeepCopy() *CSIPowerMaxRevProxyStatus {
	if in == nil {
		return nil
	}
	out := new(CSIPowerMaxRevProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerMaxSpec) DeepCopyInto(out *CSIPowerMaxSpec) {
	*out = *in
	in.Driver.DeepCopyInto(&out.Driver)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerMaxSpec.
func (in *CSIPowerMaxSpec) DeepCopy() *CSIPowerMaxSpec {
	if in == nil {
		return nil
	}
	out := new(CSIPowerMaxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerStore) DeepCopyInto(out *CSIPowerStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerStore.
func (in *CSIPowerStore) DeepCopy() *CSIPowerStore {
	if in == nil {
		return nil
	}
	out := new(CSIPowerStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIPowerStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerStoreList) DeepCopyInto(out *CSIPowerStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIPowerStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerStoreList.
func (in *CSIPowerStoreList) DeepCopy() *CSIPowerStoreList {
	if in == nil {
		return nil
	}
	out := new(CSIPowerStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIPowerStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIPowerStoreSpec) DeepCopyInto(out *CSIPowerStoreSpec) {
	*out = *in
	in.Driver.DeepCopyInto(&out.Driver)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIPowerStoreSpec.
func (in *CSIPowerStoreSpec) DeepCopy() *CSIPowerStoreSpec {
	if in == nil {
		return nil
	}
	out := new(CSIPowerStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIUnity) DeepCopyInto(out *CSIUnity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIUnity.
func (in *CSIUnity) DeepCopy() *CSIUnity {
	if in == nil {
		return nil
	}
	out := new(CSIUnity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIUnity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIUnityList) DeepCopyInto(out *CSIUnityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIUnity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIUnityList.
func (in *CSIUnityList) DeepCopy() *CSIUnityList {
	if in == nil {
		return nil
	}
	out := new(CSIUnityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIUnityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIUnitySpec) DeepCopyInto(out *CSIUnitySpec) {
	*out = *in
	in.Driver.DeepCopyInto(&out.Driver)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIUnitySpec.
func (in *CSIUnitySpec) DeepCopy() *CSIUnitySpec {
	if in == nil {
		return nil
	}
	out := new(CSIUnitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIVXFlexOS) DeepCopyInto(out *CSIVXFlexOS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIVXFlexOS.
func (in *CSIVXFlexOS) DeepCopy() *CSIVXFlexOS {
	if in == nil {
		return nil
	}
	out := new(CSIVXFlexOS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIVXFlexOS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIVXFlexOSList) DeepCopyInto(out *CSIVXFlexOSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIVXFlexOS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIVXFlexOSList.
func (in *CSIVXFlexOSList) DeepCopy() *CSIVXFlexOSList {
	if in == nil {
		return nil
	}
	out := new(CSIVXFlexOSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIVXFlexOSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIVXFlexOSSpec) DeepCopyInto(out *CSIVXFlexOSSpec) {
	*out = *in
	in.Driver.DeepCopyInto(&out.Driver)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIVXFlexOSSpec.
func (in *CSIVXFlexOSSpec) DeepCopy() *CSIVXFlexOSSpec {
	if in == nil {
		return nil
	}
	out := new(CSIVXFlexOSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerTemplate) DeepCopyInto(out *ContainerTemplate) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerTemplate.
func (in *ContainerTemplate) DeepCopy() *ContainerTemplate {
	if in == nil {
		return nil
	}
	out := new(ContainerTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Driver) DeepCopyInto(out *Driver) {
	*out = *in
	in.Common.DeepCopyInto(&out.Common)
	in.Controller.DeepCopyInto(&out.Controller)
	in.Node.DeepCopyInto(&out.Node)
	if in.SideCars != nil {
		in, out := &in.SideCars, &out.SideCars
		*out = make([]ContainerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]ContainerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = make([]StorageClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnapshotClass != nil {
		in, out := &in.SnapshotClass, &out.SnapshotClass
		*out = make([]SnapshotClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Driver.
func (in *Driver) DeepCopy() *Driver {
	if in == nil {
		return nil
	}
	out := new(Driver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverStatus) DeepCopyInto(out *DriverStatus) {
	*out = *in
	in.ControllerStatus.DeepCopyInto(&out.ControllerStatus)
	in.NodeStatus.DeepCopyInto(&out.NodeStatus)
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverStatus.
func (in *DriverStatus) DeepCopy() *DriverStatus {
	if in == nil {
		return nil
	}
	out := new(DriverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastUpdate) DeepCopyInto(out *LastUpdate) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastUpdate.
func (in *LastUpdate) DeepCopy() *LastUpdate {
	if in == nil {
		return nil
	}
	out := new(LastUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkConfig) DeepCopyInto(out *LinkConfig) {
	*out = *in
	out.Primary = in.Primary
	out.Backup = in.Backup
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkConfig.
func (in *LinkConfig) DeepCopy() *LinkConfig {
	if in == nil {
		return nil
	}
	out := new(LinkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementServerConfig) DeepCopyInto(out *ManagementServerConfig) {
	*out = *in
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementServerConfig.
func (in *ManagementServerConfig) DeepCopy() *ManagementServerConfig {
	if in == nil {
		return nil
	}
	out := new(ManagementServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSchedulingConstraints) DeepCopyInto(out *PodSchedulingConstraints) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSchedulingConstraints.
func (in *PodSchedulingConstraints) DeepCopy() *PodSchedulingConstraints {
	if in == nil {
		return nil
	}
	out := new(PodSchedulingConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodStatus) DeepCopyInto(out *PodStatus) {
	*out = *in
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Starting != nil {
		in, out := &in.Starting, &out.Starting
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Stopped != nil {
		in, out := &in.Stopped, &out.Stopped
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodStatus.
func (in *PodStatus) DeepCopy() *PodStatus {
	if in == nil {
		return nil
	}
	out := new(PodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyLimits) DeepCopyInto(out *ProxyLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyLimits.
func (in *ProxyLimits) DeepCopy() *ProxyLimits {
	if in == nil {
		return nil
	}
	out := new(ProxyLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevProxyConfig) DeepCopyInto(out *RevProxyConfig) {
	*out = *in
	if in.LinkConfig != nil {
		in, out := &in.LinkConfig, &out.LinkConfig
		*out = new(LinkConfig)
		**out = **in
	}
	if in.StandAloneConfig != nil {
		in, out := &in.StandAloneConfig, &out.StandAloneConfig
		*out = new(StandAloneConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevProxyConfig.
func (in *RevProxyConfig) DeepCopy() *RevProxyConfig {
	if in == nil {
		return nil
	}
	out := new(RevProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotClass) DeepCopyInto(out *SnapshotClass) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotClass.
func (in *SnapshotClass) DeepCopy() *SnapshotClass {
	if in == nil {
		return nil
	}
	out := new(SnapshotClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandAloneConfig) DeepCopyInto(out *StandAloneConfig) {
	*out = *in
	if in.StorageArrayConfig != nil {
		in, out := &in.StorageArrayConfig, &out.StorageArrayConfig
		*out = make([]StorageArrayConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagementServerConfig != nil {
		in, out := &in.ManagementServerConfig, &out.ManagementServerConfig
		*out = make([]ManagementServerConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandAloneConfig.
func (in *StandAloneConfig) DeepCopy() *StandAloneConfig {
	if in == nil {
		return nil
	}
	out := new(StandAloneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageArrayConfig) DeepCopyInto(out *StorageArrayConfig) {
	*out = *in
	if in.ProxyCredentialSecrets != nil {
		in, out := &in.ProxyCredentialSecrets, &out.ProxyCredentialSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageArrayConfig.
func (in *StorageArrayConfig) DeepCopy() *StorageArrayConfig {
	if in == nil {
		return nil
	}
	out := new(StorageArrayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClass) DeepCopyInto(out *StorageClass) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AllowVolumeExpansion != nil {
		in, out := &in.AllowVolumeExpansion, &out.AllowVolumeExpansion
		*out = new(bool)
		**out = **in
	}
	if in.AllowedTopologies != nil {
		in, out := &in.AllowedTopologies, &out.AllowedTopologies
		*out = make([]corev1.TopologySelectorTerm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClass.
func (in *StorageClass) DeepCopy() *StorageClass {
	if in == nil {
		return nil
	}
	out := new(StorageClass)
	in.DeepCopyInto(out)
	return out
}
