general:
  vulnerabilities:
    # list of CVEs that are currently unfixed
    - CVE-2022-24407
    - CVE-2021-25741
  bestPracticeViolations:
    # list of best practies violatied that needs a fix
    - DKL-DI-0006
    - CIS-DI-0005
    - CIS-DI-0006
    - CIS-DI-0008
    - DKL-LI-0003
